### ISSUE TITLE
Please help test this PAN-OS plugin!

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-panos#1]
We'd love a Steampipe plugin to connect with PAN-OS, but don't have an environment for testing. So ... we need your help!

The plugin is a very simple build right now of just a single `panos_address_object` table. We'd like to confirm it works and find someone who can collaborate with us on testing / development of the plugin.

Please try building it per the README - https://github.com/turbot/steampipe-plugin-panos#developing and send us your feedback or bug reports!

We'd also be happy to do a screenshare to get things started :-)

**Comment by cbruno10** [comment]
Closing this issue as more tables have been added since this issue was created, but we'll always welcome any additional testing/feedback!
